# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Job:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./resto
    
    strategy:
      matrix:
        node-version: [24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: resto/package-lock.json
    - run: npm ci
    - run: npm run build --if-present
    - name: Show success message
      run: echo "Build finalizado con éxito."

  imprimir-datos:
    runs-on: ubuntu-latest
    steps:
      # Usando variables integradas en los nombres de los pasos
      - name: Saludo al desarrollador ${{ github.actor }}
        run: |
          echo "Hola ${{ github.actor }}, estás trabajando en la rama ${{ github.ref_name }}"

      # Condicional inteligente usando variables
      - name: Solo se ejecuta si estamos en la rama principal
        if: github.ref_name == 'main'
        run: echo "¡Alerta! Ejecutando un cambio crítico en la rama principal."

# TAREA 1: Corre siempre para verificar que el código no tenga errores
  ejecutar-pruebas:
    runs-on: ubuntu-latest
    needs: imprimir-datos # Espera a que se impriman los datos antes de correr las pruebas
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Correr Tests
        run: echo "Pasando pruebas unitarias obligatorias..."

  # TAREA 2: SOLO corre si los cambios se subieron a la rama 'main'
  desplegar-produccion:
    runs-on: ubuntu-latest
    needs: ejecutar-pruebas # Espera a que las pruebas pasen primero
    
    # AQUÍ ESTÁ EL CONDICIONAL DE RAMA:
    if: github.ref_name == 'main'
    
    steps:
      - name: Desplegar App
        run: echo "🚀 Desplegando en los servidores de producción porque estamos en MAIN!"